// ==UserScript==
// @name         tinyShield
// @encoding     utf-8
// @namespace    https://github.com/FilteringDev/tinyShield
// @homepageURL  https://github.com/FilteringDev/tinyShield
// @supportURL   https://github.com/FilteringDev/tinyShield/issues
// @updateURL    https://cdn.jsdelivr.net/npm/@filteringdev/tinyshield@latest/dist/tinyShield.user.js
// @downloadURL  https://cdn.jsdelivr.net/npm/@filteringdev/tinyshield@latest/dist/tinyShield.user.js
// @license      MIT
//
// @version      2.0.22
// @author       PiQuark6046 and contributors
//
// @match        *://ygosu.com/*
// @match        *://m.ygosu.com/*
// @match        *://ad-shield.io/*
// @match        *://feedclick.net/*
// @match        *://sportalkorea.com/*
// @match        *://*.sportalkorea.com/*
// @match        *://enetnews.co.kr/*
// @match        *://*.enetnews.co.kr/*
// @match        *://edaily.co.kr/*
// @match        *://*.edaily.co.kr/*
// @match        *://economist.co.kr/*
// @match        *://*.economist.co.kr/*
// @match        *://etoday.co.kr/*
// @match        *://*.etoday.co.kr/*
// @match        *://hankyung.com/*
// @match        *://*.hankyung.com/*
// @match        *://isplus.com/*
// @match        *://*.isplus.com/*
// @match        *://hometownstation.com/*
// @match        *://*.hometownstation.com/*
// @match        *://inven.co.kr/*
// @match        *://*.inven.co.kr/*
// @match        *://loawa.com/*
// @match        *://*.loawa.com/*
// @match        *://viva100.com/*
// @match        *://*.viva100.com/*
// @match        *://joongdo.co.kr/*
// @match        *://*.joongdo.co.kr/*
// @match        *://kagit.kr/*
// @match        *://*.kagit.kr/*
// @match        *://jjang0u.com/*
// @match        *://*.jjang0u.com/*
// @match        *://cboard.net/*
// @match        *://*.cboard.net/*
// @match        *://interfootball.co.kr/*
// @match        *://*.interfootball.co.kr/*
// @match        *://fourfourtwo.co.kr/*
// @match        *://*.fourfourtwo.co.kr/*
// @match        *://newdaily.co.kr/*
// @match        *://*.newdaily.co.kr/*
// @match        *://genshinlab.com/*
// @match        *://*.genshinlab.com/*
// @match        *://thephoblographer.com/*
// @match        *://*.thephoblographer.com/*
// @match        *://dogdrip.net/*
// @match        *://*.dogdrip.net/*
// @match        *://honkailab.com/*
// @match        *://*.honkailab.com/*
// @match        *://warcraftrumbledeck.com/*
// @match        *://*.warcraftrumbledeck.com/*
// @match        *://mlbpark.donga.com/*
// @match        *://*.mlbpark.donga.com/*
// @match        *://gamingdeputy.com/*
// @match        *://*.gamingdeputy.com/*
// @match        *://thestockmarketwatch.com/*
// @match        *://*.thestockmarketwatch.com/*
// @match        *://thesaurus.net/*
// @match        *://*.thesaurus.net/*
// @match        *://forexlive.com/*
// @match        *://*.forexlive.com/*
// @match        *://tweaksforgeeks.com/*
// @match        *://*.tweaksforgeeks.com/*
// @match        *://alle-tests.nl/*
// @match        *://*.alle-tests.nl/*
// @match        *://allthetests.com/*
// @match        *://*.allthetests.com/*
// @match        *://issuya.com/*
// @match        *://*.issuya.com/*
// @match        *://maketecheasier.com/*
// @match        *://*.maketecheasier.com/*
// @match        *://motorbikecatalog.com/*
// @match        *://*.motorbikecatalog.com/*
// @match        *://automobile-catalog.com/*
// @match        *://*.automobile-catalog.com/*
// @match        *://topstarnews.net/*
// @match        *://*.topstarnews.net/*
// @match        *://worldhistory.org/*
// @match        *://*.worldhistory.org/*
// @match        *://etnews.com/*
// @match        *://*.etnews.com/*
// @match        *://iusm.co.kr/*
// @match        *://*.iusm.co.kr/*
// @match        *://etoland.co.kr/*
// @match        *://*.etoland.co.kr/*
// @match        *://apkmirror.com/*
// @match        *://*.apkmirror.com/*
// @match        *://uttranews.com/*
// @match        *://*.uttranews.com/*
// @match        *://fntimes.com/*
// @match        *://*.fntimes.com/*
// @match        *://javatpoint.com/*
// @match        *://*.javatpoint.com/*
// @match        *://text-compare.com/*
// @match        *://*.text-compare.com/*
// @match        *://vipotv.com/*
// @match        *://*.vipotv.com/*
// @match        *://lamire.jp/*
// @match        *://*.lamire.jp/*
// @match        *://dt.co.kr/*
// @match        *://*.dt.co.kr/*
// @match        *://g-enews.*/*
// @match        *://*.g-enews.*/*
// @match        *://allthekingz.com/*
// @match        *://*.allthekingz.com/*
// @match        *://gadgets360.com/*
// @match        *://*.gadgets360.com/*
// @match        *://sports.hankooki.com/*
// @match        *://*.sports.hankooki.com/*
// @match        *://ajunews.com/*
// @match        *://*.ajunews.com/*
// @match        *://munhwa.com/*
// @match        *://*.munhwa.com/*
// @match        *://zal.kr/*
// @match        *://*.zal.kr/*
// @match        *://wfmz.com/*
// @match        *://*.wfmz.com/*
// @match        *://thestar.co.uk/*
// @match        *://*.thestar.co.uk/*
// @match        *://yorkshirepost.co.uk/*
// @match        *://*.yorkshirepost.co.uk/*
// @match        *://mydaily.co.kr/*
// @match        *://*.mydaily.co.kr/*
// @match        *://raenonx.cc/*
// @match        *://*.raenonx.cc/*
// @match        *://ndtvprofit.com/*
// @match        *://*.ndtvprofit.com/*
// @match        *://badmouth1.com/*
// @match        *://*.badmouth1.com/*
// @match        *://logicieleducatif.fr/*
// @match        *://*.logicieleducatif.fr/*
// @match        *://taxguru.in/*
// @match        *://*.taxguru.in/*
// @match        *://islamicfinder.org/*
// @match        *://*.islamicfinder.org/*
// @match        *://aikatu.jp/*
// @match        *://*.aikatu.jp/*
// @match        *://secure-signup.net/*
// @match        *://*.secure-signup.net/*
// @match        *://globalrph.com/*
// @match        *://*.globalrph.com/*
// @match        *://sportsrec.com/*
// @match        *://*.sportsrec.com/*
// @match        *://reportera.co.kr/*
// @match        *://*.reportera.co.kr/*
// @match        *://slobodnadalmacija.hr/*
// @match        *://*.slobodnadalmacija.hr/*
// @match        *://carscoops.com/*
// @match        *://*.carscoops.com/*
// @match        *://indiatimes.com/*
// @match        *://*.indiatimes.com/*
// @match        *://flatpanelshd.com/*
// @match        *://*.flatpanelshd.com/*
// @match        *://sportsseoul.com/*
// @match        *://*.sportsseoul.com/*
// @match        *://gloria.hr/*
// @match        *://*.gloria.hr/*
// @match        *://videogamemods.com/*
// @match        *://*.videogamemods.com/*
// @match        *://adintrend.tv/*
// @match        *://ark-unity.com/*
// @match        *://*.ark-unity.com/*
// @match        *://cool-style.com.tw/*
// @match        *://*.cool-style.com.tw/*
// @match        *://dziennik.pl/*
// @match        *://*.dziennik.pl/*
// @match        *://eurointegration.com.ua/*
// @match        *://*.eurointegration.com.ua/*
// @match        *://jin115.com/*
// @match        *://*.jin115.com/*
// @match        *://onlinegdb.com/*
// @match        *://*.onlinegdb.com/*
// @match        *://winfuture.de/*
// @match        *://*.winfuture.de/*
// @match        *://hoyme.jp/*
// @match        *://*.hoyme.jp/*
// @match        *://pravda.com.ua/*
// @match        *://*.pravda.com.ua/*
// @match        *://freemcserver.net/*
// @match        *://*.freemcserver.net/*
// @match        *://esuteru.com/*
// @match        *://*.esuteru.com/*
// @match        *://pressian.com/*
// @match        *://*.pressian.com/*
// @match        *://blog.livedoor.jp/*
// @match        *://*.blog.jp/*
// @match        *://*.diary.to/*
// @match        *://*.officialblog.jp/*
// @match        *://itainews.com/*
// @match        *://*.itainews.com/*
// @match        *://infinityfree.com/*
// @match        *://*.infinityfree.com/*
// @match        *://wort-suchen.de/*
// @match        *://*.wort-suchen.de/*
// @match        *://dramabeans.com/*
// @match        *://*.dramabeans.com/*
// @match        *://word-grabber.com/*
// @match        *://*.word-grabber.com/*
// @match        *://palabr.as/*
// @match        *://*.palabr.as/*
// @match        *://motscroises.fr/*
// @match        *://*.motscroises.fr/*
// @match        *://cruciverba.it/*
// @match        *://*.cruciverba.it/*
// @match        *://missyusa.com/*
// @match        *://*.missyusa.com/*
// @match        *://smsonline.cloud/*
// @match        *://*.smsonline.cloud/*
// @match        *://crosswordsolver.com/*
// @match        *://*.crosswordsolver.com/*
// @match        *://heureka.cz/*
// @match        *://*.heureka.cz/*
// @match        *://oradesibiu.ro/*
// @match        *://*.oradesibiu.ro/*
// @match        *://oeffnungszeitenbuch.de/*
// @match        *://*.oeffnungszeitenbuch.de/*
// @match        *://the-crossword-solver.com/*
// @match        *://*.the-crossword-solver.com/*
// @match        *://woxikon.*/*
// @match        *://*.woxikon.*/*
// @match        *://oraridiapertura24.it/*
// @match        *://*.oraridiapertura24.it/*
// @match        *://laleggepertutti.it/*
// @match        *://*.laleggepertutti.it/*
// @match        *://*.livedoor.biz/*
// @match        *://livedoor.biz/*
// @match        *://*.livedoor.blog/*
// @match        *://onecall2ch.com/*
// @match        *://*.onecall2ch.com/*
// @match        *://*.2chblog.jp/*
// @match        *://2chblog.jp/*
// @match        *://ondemandkorea.com/*
// @match        *://*.ondemandkorea.com/*
// @match        *://economictimes.com/*
// @match        *://*.economictimes.com/*
// @match        *://mynet.com/*
// @match        *://*.mynet.com/*
// @match        *://talkwithstranger.com/*
// @match        *://*.talkwithstranger.com/*
// @match        *://petitfute.com/*
// @match        *://*.petitfute.com/*
// @match        *://netzwelt.de/*
// @match        *://*.netzwelt.de/*
// @match        *://convertcase.net/*
// @match        *://*.convertcase.net/*
// @match        *://picrew.me/*
// @match        *://*.picrew.me/*
// @match        *://rostercon.com/*
// @match        *://*.rostercon.com/*
// @match        *://suzusoku.blog.jp/*
// @match        *://kreuzwortraetsel.de/*
// @match        *://*.kreuzwortraetsel.de/*
// @match        *://slashdot.org/*
// @match        *://*.slashdot.org/*
// @match        *://yutura.net/*
// @match        *://*.yutura.net/*
// @match        *://jutarnji.hr/*
// @match        *://*.jutarnji.hr/*
// @match        *://sourceforge.net/*
// @match        *://*.sourceforge.net/*
// @match        *://manta.com/*
// @match        *://*.manta.com/*
// @match        *://tportal.hr/*
// @match        *://*.tportal.hr/*
// @match        *://horairesdouverture24.fr/*
// @match        *://*.horairesdouverture24.fr/*
// @match        *://nyitvatartas24.hu/*
// @match        *://*.nyitvatartas24.hu/*
// @match        *://verkaufsoffener-sonntag.com/*
// @match        *://*.verkaufsoffener-sonntag.com/*
// @match        *://raetsel-hilfe.de/*
// @match        *://*.raetsel-hilfe.de/*
// @match        *://zeta-ai.io/*
// @match        *://*.zeta-ai.io/*
// @match        *://zagreb.info/*
// @match        *://*.zagreb.info/*
// @match        *://powerpyx.com/*
// @match        *://*.powerpyx.com/*
// @match        *://webdesignledger.com/*
// @match        *://*.webdesignledger.com/*
// @match        *://dolldivine.com/*
// @match        *://*.dolldivine.com/*
// @match        *://cinema.com.my/*
// @match        *://*.cinema.com.my/*
// @match        *://lacuarta.com/*
// @match        *://*.lacuarta.com/*
// @match        *://wetteronline.de/*
// @match        *://*.wetteronline.de/*
// @match        *://yugioh-starlight.com/*
// @match        *://*.yugioh-starlight.com/*
// @match        *://syosetu.com/*
// @match        *://*.syosetu.com/*
// @match        *://lovelive-petitsoku.com/*
// @match        *://*.lovelive-petitsoku.com/*
// @match        *://autoby.jp/*
// @match        *://*.autoby.jp/*
// @match        *://giornalone.it/*
// @match        *://*.giornalone.it/*
// @match        *://ap7am.com/*
// @match        *://*.ap7am.com/*
// @match        *://dnevno.hr/*
// @match        *://*.dnevno.hr/*
// @match        *://mediaindonesia.com/*
// @match        *://*.mediaindonesia.com/*
// @match        *://daily.co.jp/*
// @match        *://*.daily.co.jp/*
// @match        *://forsal.pl/*
// @match        *://*.forsal.pl/*
// @match        *://trilltrill.jp/*
// @match        *://*.trilltrill.jp/*
// @match        *://bg-mania.jp/*
// @match        *://*.bg-mania.jp/*
// @match        *://j-town.net/*
// @match        *://*.j-town.net/*
// @match        *://gazetaprawna.pl/*
// @match        *://*.gazetaprawna.pl/*
// @match        *://game8.jp/*
// @match        *://*.game8.jp/*
// @match        *://mamastar.jp/*
// @match        *://*.mamastar.jp/*
// @match        *://tvtv.us/*
// @match        *://*.tvtv.us/*
// @match        *://j-cast.com/*
// @match        *://*.j-cast.com/*
// @match        *://tvtv.ca/*
// @match        *://*.tvtv.ca/*
// @match        *://mariowiki.com/*
// @match        *://*.mariowiki.com/*
// @match        *://watchdocumentaries.com/*
// @match        *://*.watchdocumentaries.com/*
// @match        *://kompasiana.com/*
// @match        *://*.kompasiana.com/*
// @match        *://quefaire.be/*
// @match        *://*.quefaire.be/*
// @match        *://dailydot.com/*
// @match        *://*.dailydot.com/*
// @match        *://jablickar.cz/*
// @match        *://*.jablickar.cz/*
// @match        *://jmty.jp/*
// @match        *://*.jmty.jp/*
// @match        *://nikkansports.com/*
// @match        *://*.nikkansports.com/*
// @match        *://bleepingcomputer.com/*
// @match        *://*.bleepingcomputer.com/*
// @match        *://samsungmagazine.eu/*
// @match        *://*.samsungmagazine.eu/*
// @match        *://kurashiru.com/*
// @match        *://*.kurashiru.com/*
// @match        *://gundamlog.com/*
// @match        *://*.gundamlog.com/*
// @match        *://jnews1.com/*
// @match        *://*.jnews1.com/*
// @match        *://inutomo11.com/*
// @match        *://*.inutomo11.com/*
// @match        *://alfalfalfa.com/*
// @match        *://*.alfalfalfa.com/*
// @match        *://46matome.net/*
// @match        *://*.46matome.net/*
// @match        *://anihatsu.com/*
// @match        *://*.anihatsu.com/*
// @match        *://aqua2ch.net/*
// @match        *://*.aqua2ch.net/*
// @match        *://danseisama.com/*
// @match        *://*.danseisama.com/*
// @match        *://dareda.net/*
// @match        *://*.dareda.net/*
// @match        *://digital-thread.com/*
// @match        *://*.digital-thread.com/*
// @match        *://fgochaldeas.com/*
// @match        *://*.fgochaldeas.com/*
// @match        *://golog.jp/*
// @match        *://*.golog.jp/*
// @match        *://heartlife-matome.com/*
// @match        *://*.heartlife-matome.com/*
// @match        *://ikarishintou.com/*
// @match        *://*.ikarishintou.com/*
// @match        *://imihu.net/*
// @match        *://*.imihu.net/*
// @match        *://jyoseisama.com/*
// @match        *://*.jyoseisama.com/*
// @match        *://kijoden.com/*
// @match        *://*.kijoden.com/*
// @match        *://kijyokatu.com/*
// @match        *://*.kijyokatu.com/*
// @match        *://kitimama-matome.net/*
// @match        *://*.kitimama-matome.net/*
// @match        *://kitizawa.com/*
// @match        *://*.kitizawa.com/*
// @match        *://kotaro269.com/*
// @match        *://*.kotaro269.com/*
// @match        *://kyousoku.net/*
// @match        *://*.kyousoku.net/*
// @match        *://matomeblade.com/*
// @match        *://*.matomeblade.com/*
// @match        *://mojomojo-licarca.com/*
// @match        *://*.mojomojo-licarca.com/*
// @match        *://news-buzz1.com/*
// @match        *://*.news-buzz1.com/*
// @match        *://onihimechan.com/*
// @match        *://*.onihimechan.com/*
// @match        *://orusoku.com/*
// @match        *://*.orusoku.com/*
// @match        *://outdoormatome.com/*
// @match        *://*.outdoormatome.com/*
// @match        *://squallchannel.com/*
// @match        *://*.squallchannel.com/*
// @match        *://sukattojapan.com/*
// @match        *://*.sukattojapan.com/*
// @match        *://sumaburayasan.com/*
// @match        *://*.sumaburayasan.com/*
// @match        *://vipnews.jp/*
// @match        *://*.vipnews.jp/*
// @match        *://vtubernews.jp/*
// @match        *://*.vtubernews.jp/*
// @match        *://watarukiti.com/*
// @match        *://*.watarukiti.com/*
// @match        *://nana-press.com/*
// @match        *://*.nana-press.com/*
// @match        *://animanch.com/*
// @match        *://*.animanch.com/*
// @match        *://matometemitatta.com/*
// @match        *://*.matometemitatta.com/*
// @match        *://2monkeys.jp/*
// @match        *://*.2monkeys.jp/*
// @match        *://all-nationz.com/*
// @match        *://*.all-nationz.com/*
// @match        *://doorblog.jp/*
// @match        *://*.doorblog.jp/*
// @match        *://liblo.jp/*
// @match        *://*.liblo.jp/*
// @match        *://fesoku.net/*
// @match        *://*.fesoku.net/*
// @match        *://fiveslot777.com/*
// @match        *://*.fiveslot777.com/*
// @match        *://gamejksokuhou.com/*
// @match        *://*.gamejksokuhou.com/*
// @match        *://gekiyaku.com/*
// @match        *://*.gekiyaku.com/*
// @match        *://girlsreport.net/*
// @match        *://*.girlsreport.net/*
// @match        *://girlsvip-matome.com/*
// @match        *://*.girlsvip-matome.com/*
// @match        *://grasoku.com/*
// @match        *://*.grasoku.com/*
// @match        *://keyakizaka46matomemory.net/*
// @match        *://*.keyakizaka46matomemory.net/*
// @match        *://kidan-m.com/*
// @match        *://*.kidan-m.com/*
// @match        *://kijolifehack.com/*
// @match        *://*.kijolifehack.com/*
// @match        *://kijomatomelog.com/*
// @match        *://*.kijomatomelog.com/*
// @match        *://kijyomatome.com/*
// @match        *://*.kijyomatome.com/*
// @match        *://kijyomatome-ch.com/*
// @match        *://*.kijyomatome-ch.com/*
// @match        *://konoyubitomare.jp/*
// @match        *://*.konoyubitomare.jp/*
// @match        *://ldblog.jp/*
// @match        *://*.ldblog.jp/*
// @match        *://matomelotte.com/*
// @match        *://*.matomelotte.com/*
// @match        *://netatama.net/*
// @match        *://*.netatama.net/*
// @match        *://norisoku.com/*
// @match        *://*.norisoku.com/*
// @match        *://ocsoku.com/*
// @match        *://*.ocsoku.com/*
// @match        *://okusama-kijyo.com/*
// @match        *://*.okusama-kijyo.com/*
// @match        *://otoko-honne.com/*
// @match        *://*.otoko-honne.com/*
// @match        *://oumaga-times.com/*
// @match        *://*.oumaga-times.com/*
// @match        *://pachinkopachisro.com/*
// @match        *://*.pachinkopachisro.com/*
// @match        *://paranormal-ch.com/*
// @match        *://*.paranormal-ch.com/*
// @match        *://recosoku.com/*
// @match        *://*.recosoku.com/*
// @match        *://saikyo-jump.com/*
// @match        *://*.saikyo-jump.com/*
// @match        *://shuraba-matome.com/*
// @match        *://*.shuraba-matome.com/*
// @match        *://ske48matome.net/*
// @match        *://*.ske48matome.net/*
// @match        *://uwakich.com/*
// @match        *://*.uwakich.com/*
// @match        *://uwakitaiken.com/*
// @match        *://*.uwakitaiken.com/*
// @match        *://choco0202.work/*
// @match        *://*.choco0202.work/*
// @match        *://exawarosu.net/*
// @match        *://*.exawarosu.net/*
// @match        *://honyaku-channel.net/*
// @match        *://*.honyaku-channel.net/*
// @match        *://jisaka.com/*
// @match        *://*.jisaka.com/*
// @match        *://kijolariat.net/*
// @match        *://*.kijolariat.net/*
// @match        *://kijyomita.com/*
// @match        *://*.kijyomita.com/*
// @match        *://kirarafan.com/*
// @match        *://*.kirarafan.com/*
// @match        *://nandemo-uketori.com/*
// @match        *://*.nandemo-uketori.com/*
// @match        *://npb-news.com/*
// @match        *://*.npb-news.com/*
// @match        *://letemsvetemapplem.eu/*
// @match        *://*.letemsvetemapplem.eu/*
// @match        *://transparentnevada.com/*
// @match        *://*.transparentnevada.com/*
// @match        *://roleplay.me/*
// @match        *://*.roleplay.me/*
// @match        *://aniroleplay.com/*
// @match        *://*.aniroleplay.com/*
// @match        *://transparentcalifornia.com/*
// @match        *://*.transparentcalifornia.com/*
// @match        *://kyoteibiyori.com/*
// @match        *://*.kyoteibiyori.com/*
// @match        *://iza.ne.jp/*
// @match        *://*.iza.ne.jp/*
// @match        *://chanto.jp.net/*
// @match        *://*.chanto.jp.net/*
// @match        *://malaymail.com/*
// @match        *://*.malaymail.com/*
// @match        *://ranking.net/*
// @match        *://*.ranking.net/*
// @match        *://cinetrafic.fr/*
// @match        *://*.cinetrafic.fr/*
// @match        *://cocokara-next.com/*
// @match        *://*.cocokara-next.com/*
// @match        *://computerfrage.net/*
// @match        *://*.computerfrage.net/*
// @match        *://autofrage.net/*
// @match        *://*.autofrage.net/*
// @match        *://thefreebieguy.com/*
// @match        *://*.thefreebieguy.com/*
// @match        *://lakeshowlife.com/*
// @match        *://*.lakeshowlife.com/*
// @match        *://buzzfeed.com/*
// @match        *://*.buzzfeed.com/*
// @match        *://buzzfeednews.com/*
// @match        *://*.buzzfeednews.com/*
// @match        *://thatgossip.com/*
// @match        *://*.thatgossip.com/*
// @match        *://infor.pl/*
// @match        *://*.infor.pl/*
// @match        *://livenewschat.eu/*
// @match        *://*.livenewschat.eu/*
// @match        *://reptilesmagazine.com/*
// @match        *://*.reptilesmagazine.com/*
// @match        *://akb48glabo.com/*
// @match        *://*.akb48glabo.com/*
// @match        *://blogo.jp/*
// @match        *://*.blogo.jp/*
// @match        *://chaos2ch.com/*
// @match        *://*.chaos2ch.com/*
// @match        *://crx7601.com/*
// @match        *://*.crx7601.com/*
// @match        *://football-2ch.com/*
// @match        *://*.football-2ch.com/*
// @match        *://hacchaka.net/*
// @match        *://*.hacchaka.net/*
// @match        *://itaishinja.com/*
// @match        *://*.itaishinja.com/*
// @match        *://jumpsokuhou.com/*
// @match        *://*.jumpsokuhou.com/*
// @match        *://matacoco.com/*
// @match        *://*.matacoco.com/*
// @match        *://majikichi.com/*
// @match        *://*.majikichi.com/*
// @match        *://morikinoko.com/*
// @match        *://*.morikinoko.com/*
// @match        *://news30over.com/*
// @match        *://*.news30over.com/*
// @match        *://nmb48-mtm.com/*
// @match        *://*.nmb48-mtm.com/*
// @match        *://otakomu.jp/*
// @match        *://*.otakomu.jp/*
// @match        *://s2-log.com/*
// @match        *://*.s2-log.com/*
// @match        *://vault76.info/*
// @match        *://*.vault76.info/*
// @match        *://world-fusigi.net/*
// @match        *://*.world-fusigi.net/*
// @match        *://zakuzaku911.com/*
// @match        *://*.zakuzaku911.com/*
// @match        *://zch-vip.com/*
// @match        *://*.zch-vip.com/*
// @match        *://usi32.com/*
// @match        *://*.usi32.com/*
// @match        *://kinmaweb.jp/*
// @match        *://*.kinmaweb.jp/*
// @match        *://play-games.com/*
// @match        *://*.play-games.com/*
// @match        *://huffpost.com/*
// @match        *://*.huffpost.com/*
// @match        *://lifehacker.jp/*
// @match        *://*.lifehacker.jp/*
// @match        *://minkou.jp/*
// @match        *://*.minkou.jp/*
// @match        *://nikkan-gendai.com/*
// @match        *://*.nikkan-gendai.com/*
// @match        *://niice-woker.com/*
// @match        *://*.niice-woker.com/*
// @match        *://blogmura.com/*
// @match        *://*.blogmura.com/*
// @match        *://si.com/*
// @match        *://*.si.com/*
// @match        *://gardeningsoul.com/*
// @match        *://*.gardeningsoul.com/*
// @match        *://filmibeat.com/*
// @match        *://*.filmibeat.com/*
// @match        *://goodreturns.in/*
// @match        *://*.goodreturns.in/*
// @match        *://mykhel.com/*
// @match        *://*.mykhel.com/*
// @match        *://laposte.net/*
// @match        *://*.laposte.net/*
// @match        *://vippers.jp/*
// @match        *://*.vippers.jp/*
// @match        *://drweil.com/*
// @match        *://*.drweil.com/*
// @match        *://ufret.jp/*
// @match        *://*.ufret.jp/*
// @match        *://op.gg/*
// @match        *://*.op.gg/*
// @match        *://lerobert.com/*
// @match        *://*.lerobert.com/*
// @match        *://picks.my/*
// @match        *://*.picks.my/*
// @match        *://fansided.com/*
// @match        *://*.fansided.com/*
// @match        *://donbalon.com/*
// @match        *://*.donbalon.com/*
// @match        *://dropgame.jp/*
// @match        *://*.dropgame.jp/*
// @match        *://footballtransfer.ru/*
// @match        *://*.footballtransfer.ru/*
// @match        *://relevantmagazine.com/*
// @match        *://*.relevantmagazine.com/*
// @match        *://tbsradio.jp/*
// @match        *://*.tbsradio.jp/*
// @match        *://kobe-journal.com/*
// @match        *://*.kobe-journal.com/*
// @match        *://sankei.com/*
// @match        *://*.sankei.com/*
// @match        *://alc.co.jp/*
// @match        *://*.alc.co.jp/*
// @match        *://gigafile.nu/*
// @match        *://*.gigafile.nu/*
// @match        *://sanspo.com/*
// @match        *://*.sanspo.com/*
// @match        *://zakzak.co.jp/*
// @match        *://*.zakzak.co.jp/*
// @match        *://nosv.org/*
// @match        *://*.nosv.org/*
// @match        *://easyhindityping.com/*
// @match        *://*.easyhindityping.com/*
// @match        *://lawyersgunsmoneyblog.com/*
// @match        *://*.lawyersgunsmoneyblog.com/*
// @match        *://operawire.com/*
// @match        *://*.operawire.com/*
// @match        *://fxstreet.es/*
// @match        *://*.fxstreet.es/*
// @match        *://fxstreet.it/*
// @match        *://*.fxstreet.it/*
// @match        *://fxstreet-id.com/*
// @match        *://*.fxstreet-id.com/*
// @match        *://fxstreet.*/*
// @match        *://*.fxstreet.*/*
// @match        *://373news.com/*
// @match        *://*.373news.com/*
// @match        *://muragon.com/*
// @match        *://*.muragon.com/*
// @match        *://aucfree.com/*
// @match        *://*.aucfree.com/*
// @match        *://natalie.mu/*
// @match        *://*.natalie.mu/*
// @match        *://oxfordlearnersdictionaries.com/*
// @match        *://*.oxfordlearnersdictionaries.com/*
// @match        *://motor-talk.de/*
// @match        *://*.motor-talk.de/*
// @match        *://niketalk.com/*
// @match        *://*.niketalk.com/*
// @match        *://gutefrage.net/*
// @match        *://*.gutefrage.net/*
// @match        *://langenscheidt.com/*
// @match        *://*.langenscheidt.com/*
// @match        *://pashplus.jp/*
// @match        *://*.pashplus.jp/*
// @match        *://grapee.jp/*
// @match        *://*.grapee.jp/*
// @match        *://yakkun.com/*
// @match        *://*.yakkun.com/*
// @match        *://young-machine.com/*
// @match        *://*.young-machine.com/*
// @match        *://jikayosha.jp/*
// @match        *://*.jikayosha.jp/*
// @match        *://luremaga.jp/*
// @match        *://*.luremaga.jp/*
// @match        *://traicy.com/*
// @match        *://*.traicy.com/*
// @match        *://collinsdictionary.com/*
// @match        *://*.collinsdictionary.com/*
// @match        *://ldoceonline.com/*
// @match        *://*.ldoceonline.com/*
// @match        *://tunebat.com/*
// @match        *://*.tunebat.com/*
// @match        *://bab.la/*
// @match        *://*.bab.la/*
// @match        *://tz.de/*
// @match        *://*.tz.de/*
// @match        *://cambridge.org/*
// @match        *://*.cambridge.org/*
// @match        *://sportlerfrage.net/*
// @match        *://*.sportlerfrage.net/*
// @match        *://reisefrage.net/*
// @match        *://*.reisefrage.net/*
// @match        *://motorradfrage.net/*
// @match        *://*.motorradfrage.net/*
// @match        *://gesundheitsfrage.net/*
// @match        *://*.gesundheitsfrage.net/*
// @match        *://finanzfrage.net/*
// @match        *://*.finanzfrage.net/*
// @match        *://newsinlevels.com/*
// @match        *://*.newsinlevels.com/*
// @match        *://ev-times.com/*
// @match        *://*.ev-times.com/*
// @match        *://mainichi.jp/*
// @match        *://*.mainichi.jp/*
// @match        *://worldjournal.com/*
// @match        *://*.worldjournal.com/*
// @match        *://southhemitv.com/*
// @match        *://*.southhemitv.com/*
// @match        *://cults3d.com/*
// @match        *://*.cults3d.com/*
// @match        *://newsweekjapan.jp/*
// @match        *://*.newsweekjapan.jp/*
// @match        *://optionsprofitcalculator.com/*
// @match        *://*.optionsprofitcalculator.com/*
// @match        *://as-web.jp/*
// @match        *://*.as-web.jp/*
// @match        *://thedigestweb.com/*
// @match        *://*.thedigestweb.com/*
// @match        *://sutekinakijo.com/*
// @match        *://*.sutekinakijo.com/*
// @match        *://onlineradiobox.com/*
// @match        *://*.onlineradiobox.com/*
// @match        *://hotcopper.com.au/*
// @match        *://*.hotcopper.com.au/*
// @match        *://soccerdigestweb.com/*
// @match        *://*.soccerdigestweb.com/*
// @match        *://scribens.*/*
// @match        *://*.scribens.*/*
// @match        *://dailynewshungary.com/*
// @match        *://*.dailynewshungary.com/*
// @match        *://mentalfloss.com/*
// @match        *://*.mentalfloss.com/*
// @match        *://judgehype.com/*
// @match        *://*.judgehype.com/*
// @match        *://idokep.hu/*
// @match        *://*.idokep.hu/*
// @match        *://baseballchannel.jp/*
// @match        *://*.baseballchannel.jp/*
// @match        *://nishinippon.co.jp/*
// @match        *://*.nishinippon.co.jp/*
// @match        *://footballchannel.jp/*
// @match        *://*.footballchannel.jp/*
// @match        *://eigachannel.jp/*
// @match        *://*.eigachannel.jp/*
// @match        *://tweaktown.com/*
// @match        *://*.tweaktown.com/*
// @match        *://kr-weathernews.com/*
// @match        *://*.kr-weathernews.com/*
// @match        *://nouvelobs.com/*
// @match        *://*.nouvelobs.com/*
// @match        *://autoc-one.jp/*
// @match        *://*.autoc-one.jp/*
// @match        *://bien.hu/*
// @match        *://*.bien.hu/*
// @match        *://hb-nippon.com/*
// @match        *://*.hb-nippon.com/*
// @match        *://j7p.jp/*
// @match        *://*.j7p.jp/*
// @match        *://leckerschmecker.me/*
// @match        *://*.leckerschmecker.me/*
// @match        *://mahjongchest.com/*
// @match        *://*.mahjongchest.com/*
// @match        *://meteo60.fr/*
// @match        *://*.meteo60.fr/*
// @match        *://minesweeperquest.com/*
// @match        *://*.minesweeperquest.com/*
// @match        *://moin.de/*
// @match        *://*.moin.de/*
// @match        *://puzzlegarage.com/*
// @match        *://*.puzzlegarage.com/*
// @match        *://solitairehut.com/*
// @match        *://*.solitairehut.com/*
// @match        *://sportanalytic.com/*
// @match        *://*.sportanalytic.com/*
// @match        *://twn.hu/*
// @match        *://*.twn.hu/*
// @match        *://gifu-np.co.jp/*
// @match        *://*.gifu-np.co.jp/*
// @match        *://hotcopper.co.nz/*
// @match        *://*.hotcopper.co.nz/*
// @match        *://vimm.net/*
// @match        *://*.vimm.net/*
// @match        *://cesoirtv.com/*
// @match        *://*.cesoirtv.com/*
// @match        *://kurashinista.jp/*
// @match        *://*.kurashinista.jp/*
// @match        *://nationaltoday.com/*
// @match        *://*.nationaltoday.com/*
// @match        *://mathplayzone.com/*
// @match        *://*.mathplayzone.com/*
// @match        *://newser.com/*
// @match        *://*.newser.com/*
// @match        *://zerkalo.io/*
// @match        *://*.zerkalo.io/*
// @match        *://pons.com/*
// @match        *://*.pons.com/*
// @match        *://wisevoter.com/*
// @match        *://*.wisevoter.com/*
// @match        *://hang.hu/*
// @match        *://*.hang.hu/*
// @match        *://dreamchance.net/*
// @match        *://*.dreamchance.net/*
// @match        *://raider.io/*
// @match        *://*.raider.io/*
// @match        *://gentosha-go.com/*
// @match        *://*.gentosha-go.com/*
// @match        *://oricon.co.jp/*
// @match        *://*.oricon.co.jp/*
// @match        *://gbatemp.net/*
// @match        *://*.gbatemp.net/*
// @match        *://jiji.com/*
// @match        *://*.jiji.com/*
// @match        *://itmedia.co.jp/*
// @match        *://*.itmedia.co.jp/*
// @match        *://boredpanda.com/*
// @match        *://*.boredpanda.com/*
// @match        *://actugaming.net/*
// @match        *://*.actugaming.net/*
// @match        *://culturequizz.com/*
// @match        *://*.culturequizz.com/*
// @match        *://dallashoopsjournal.com/*
// @match        *://*.dallashoopsjournal.com/*
// @match        *://ecranlarge.com/*
// @match        *://*.ecranlarge.com/*
// @match        *://mafab.hu/*
// @match        *://*.mafab.hu/*
// @match        *://popdaily.com.tw/*
// @match        *://*.popdaily.com.tw/*
// @match        *://statecollege.com/*
// @match        *://*.statecollege.com/*
// @match        *://wattedoen.be/*
// @match        *://*.wattedoen.be/*
// @match        *://uscreditcardguide.com/*
// @match        *://*.uscreditcardguide.com/*
// @match        *://quizlet.com/*
// @match        *://*.quizlet.com/*
// @match        *://tbs.co.jp/*
// @match        *://*.tbs.co.jp/*
// @match        *://notebookcheck.com/*
// @match        *://*.notebookcheck.com/*
// @match        *://wetter.com/*
// @match        *://*.wetter.com/*
// @match        *://90min.com/*
// @match        *://*.90min.com/*
// @match        *://12thmanrising.com/*
// @match        *://*.12thmanrising.com/*
// @match        *://1428elm.com/*
// @match        *://*.1428elm.com/*
// @match        *://8points9seconds.com/*
// @match        *://*.8points9seconds.com/*
// @match        *://acceptthisrose.com/*
// @match        *://*.acceptthisrose.com/*
// @match        *://airalamo.com/*
// @match        *://*.airalamo.com/*
// @match        *://allcougdup.com/*
// @match        *://*.allcougdup.com/*
// @match        *://allfortennessee.com/*
// @match        *://*.allfortennessee.com/*
// @match        *://allstokedup.com/*
// @match        *://*.allstokedup.com/*
// @match        *://allucanheat.com/*
// @match        *://*.allucanheat.com/*
// @match        *://alongmainstreet.com/*
// @match        *://*.alongmainstreet.com/*
// @match        *://amazonadviser.com/*
// @match        *://*.amazonadviser.com/*
// @match        *://animeaway.com/*
// @match        *://*.animeaway.com/*
// @match        *://apptrigger.com/*
// @match        *://*.apptrigger.com/*
// @match        *://aroundthefoghorn.com/*
// @match        *://*.aroundthefoghorn.com/*
// @match        *://aroyalpain.com/*
// @match        *://*.aroyalpain.com/*
// @match        *://arrowheadaddict.com/*
// @match        *://*.arrowheadaddict.com/*
// @match        *://artofgears.com/*
// @match        *://*.artofgears.com/*
// @match        *://askeverest.com/*
// @match        *://*.askeverest.com/*
// @match        *://audiophix.com/*
// @match        *://*.audiophix.com/*
// @match        *://autzenzoo.com/*
// @match        *://*.autzenzoo.com/*
// @match        *://awaybackgone.com/*
// @match        *://*.awaybackgone.com/*
// @match        *://awinninghabit.com/*
// @match        *://*.awinninghabit.com/*
// @match        *://badgerofhonor.com/*
// @match        *://*.badgerofhonor.com/*
// @match        *://balldurham.com/*
// @match        *://*.balldurham.com/*
// @match        *://bamahammer.com/*
// @match        *://*.bamahammer.com/*
// @match        *://bamsmackpow.com/*
// @match        *://*.bamsmackpow.com/*
// @match        *://bayernstrikes.com/*
// @match        *://*.bayernstrikes.com/*
// @match        *://bealestreetbears.com/*
// @match        *://*.bealestreetbears.com/*
// @match        *://beargoggleson.com/*
// @match        *://*.beargoggleson.com/*
// @match        *://beaverbyte.com/*
// @match        *://*.beaverbyte.com/*
// @match        *://behindthebuckpass.com/*
// @match        *://*.behindthebuckpass.com/*
// @match        *://beyondtheflag.com/*
// @match        *://*.beyondtheflag.com/*
// @match        *://bigredlouie.com/*
// @match        *://*.bigredlouie.com/*
// @match        *://birdswatcher.com/*
// @match        *://*.birdswatcher.com/*
// @match        *://blackandteal.com/*
// @match        *://*.blackandteal.com/*
// @match        *://blackhawkup.com/*
// @match        *://*.blackhawkup.com/*
// @match        *://blackoutdallas.com/*
// @match        *://*.blackoutdallas.com/*
// @match        *://bladesofteal.com/*
// @match        *://*.bladesofteal.com/*
// @match        *://bleedinblue.com/*
// @match        *://*.bleedinblue.com/*
// @match        *://bloggingdirty.com/*
// @match        *://*.bloggingdirty.com/*
// @match        *://blogoflegends.com/*
// @match        *://*.blogoflegends.com/*
// @match        *://blogredmachine.com/*
// @match        *://*.blogredmachine.com/*
// @match        *://bluelinestation.com/*
// @match        *://*.bluelinestation.com/*
// @match        *://bluemanhoop.com/*
// @match        *://*.bluemanhoop.com/*
// @match        *://boltbeat.com/*
// @match        *://*.boltbeat.com/*
// @match        *://boltsbythebay.com/*
// @match        *://*.boltsbythebay.com/*
// @match        *://bosoxinjection.com/*
// @match        *://*.bosoxinjection.com/*
// @match        *://broadstreetbuzz.com/*
// @match        *://*.broadstreetbuzz.com/*
// @match        *://buffalowdown.com/*
// @match        *://*.buffalowdown.com/*
// @match        *://bustingbrackets.com/*
// @match        *://*.bustingbrackets.com/*
// @match        *://bvbbuzz.com/*
// @match        *://*.bvbbuzz.com/*
// @match        *://calltothepen.com/*
// @match        *://*.calltothepen.com/*
// @match        *://caneswarning.com/*
// @match        *://*.caneswarning.com/*
// @match        *://cardiaccane.com/*
// @match        *://*.cardiaccane.com/*
// @match        *://catcrave.com/*
// @match        *://*.catcrave.com/*
// @match        *://causewaycrowd.com/*
// @match        *://*.causewaycrowd.com/*
// @match        *://champagneandshade.com/*
// @match        *://*.champagneandshade.com/*
// @match        *://chopchat.com/*
// @match        *://*.chopchat.com/*
// @match        *://chowderandchampions.com/*
// @match        *://*.chowderandchampions.com/*
// @match        *://cincyontheprowl.com/*
// @match        *://*.cincyontheprowl.com/*
// @match        *://claireandjamie.com/*
// @match        *://*.claireandjamie.com/*
// @match        *://claretvillans.com/*
// @match        *://*.claretvillans.com/*
// @match        *://climbingtalshill.com/*
// @match        *://*.climbingtalshill.com/*
// @match        *://clipperholics.com/*
// @match        *://*.clipperholics.com/*
// @match        *://cubbiescrib.com/*
// @match        *://*.cubbiescrib.com/*
// @match        *://culturess.com/*
// @match        *://*.culturess.com/*
// @match        *://dailyddt.com/*
// @match        *://*.dailyddt.com/*
// @match        *://dailyknicks.com/*
// @match        *://*.dailyknicks.com/*
// @match        *://dairylandexpress.com/*
// @match        *://*.dairylandexpress.com/*
// @match        *://dawgpounddaily.com/*
// @match        *://*.dawgpounddaily.com/*
// @match        *://dawindycity.com/*
// @match        *://*.dawindycity.com/*
// @match        *://dawnofthedawg.com/*
// @match        *://*.dawnofthedawg.com/*
// @match        *://dearoldgold.com/*
// @match        *://*.dearoldgold.com/*
// @match        *://deathvalleyvoice.com/*
// @match        *://*.deathvalleyvoice.com/*
// @match        *://detroitjockcity.com/*
// @match        *://*.detroitjockcity.com/*
// @match        *://devilsindetail.com/*
// @match        *://*.devilsindetail.com/*
// @match        *://diredota.com/*
// @match        *://*.diredota.com/*
// @match        *://districtondeck.com/*
// @match        *://*.districtondeck.com/*
// @match        *://dodgersway.com/*
// @match        *://*.dodgersway.com/*
// @match        *://dogoday.com/*
// @match        *://*.dogoday.com/*
// @match        *://dorksideoftheforce.com/*
// @match        *://*.dorksideoftheforce.com/*
// @match        *://dunkingwithwolves.com/*
// @match        *://*.dunkingwithwolves.com/*
// @match        *://ebonybird.com/*
// @match        *://*.ebonybird.com/*
// @match        *://editorinleaf.com/*
// @match        *://*.editorinleaf.com/*
// @match        *://everythingbarca.com/*
// @match        *://*.everythingbarca.com/*
// @match        *://everythingontap.com/*
// @match        *://*.everythingontap.com/*
// @match        *://eyesonisles.com/*
// @match        *://*.eyesonisles.com/*
// @match        *://factoryofsadness.co/*
// @match        *://*.factoryofsadness.co/*
// @match        *://fantasycpr.com/*
// @match        *://*.fantasycpr.com/*
// @match        *://fightinggobbler.com/*
// @match        *://*.fightinggobbler.com/*
// @match        *://flameforthought.com/*
// @match        *://*.flameforthought.com/*
// @match        *://flywareagle.com/*
// @match        *://*.flywareagle.com/*
// @match        *://foodsided.com/*
// @match        *://*.foodsided.com/*
// @match        *://foreverfortnite.com/*
// @match        *://*.foreverfortnite.com/*
// @match        *://fourfourcrew.com/*
// @match        *://*.fourfourcrew.com/*
// @match        *://foxesofleicester.com/*
// @match        *://*.foxesofleicester.com/*
// @match        *://friarsonbase.com/*
// @match        *://*.friarsonbase.com/*
// @match        *://garnetandcocky.com/*
// @match        *://*.garnetandcocky.com/*
// @match        *://gbmwolverine.com/*
// @match        *://*.gbmwolverine.com/*
// @match        *://geeksided.com/*
// @match        *://*.geeksided.com/*
// @match        *://gigemgazette.com/*
// @match        *://*.gigemgazette.com/*
// @match        *://glorycolorado.com/*
// @match        *://*.glorycolorado.com/*
// @match        *://gmenhq.com/*
// @match        *://*.gmenhq.com/*
// @match        *://gojoebruin.com/*
// @match        *://*.gojoebruin.com/*
// @match        *://goldengatesports.com/*
// @match        *://*.goldengatesports.com/*
// @match        *://gonepuckwild.com/*
// @match        *://*.gonepuckwild.com/*
// @match        *://greenstreethammers.com/*
// @match        *://*.greenstreethammers.com/*
// @match        *://guiltyeats.com/*
// @match        *://*.guiltyeats.com/*
// @match        *://hailfloridahail.com/*
// @match        *://*.hailfloridahail.com/*
// @match        *://hailwv.com/*
// @match        *://*.hailwv.com/*
// @match        *://halohangout.com/*
// @match        *://*.halohangout.com/*
// @match        *://hardwoodhoudini.com/*
// @match        *://*.hardwoodhoudini.com/*
// @match        *://hiddenremote.com/*
// @match        *://*.hiddenremote.com/*
// @match        *://hookemheadlines.com/*
// @match        *://*.hookemheadlines.com/*
// @match        *://hoopshabit.com/*
// @match        *://*.hoopshabit.com/*
// @match        *://hoosierstateofmind.com/*
// @match        *://*.hoosierstateofmind.com/*
// @match        *://horseshoeheroes.com/*
// @match        *://*.horseshoeheroes.com/*
// @match        *://hotspurhq.com/*
// @match        *://*.hotspurhq.com/*
// @match        *://houseofhouston.com/*
// @match        *://*.houseofhouston.com/*
// @match        *://housethathankbuilt.com/*
// @match        *://*.housethathankbuilt.com/*
// @match        *://howlinhockey.com/*
// @match        *://*.howlinhockey.com/*
// @match        *://huskercorner.com/*
// @match        *://*.huskercorner.com/*
// @match        *://insideibrox.com/*
// @match        *://*.insideibrox.com/*
// @match        *://insidetheiggles.com/*
// @match        *://*.insidetheiggles.com/*
// @match        *://insidetheloudhouse.com/*
// @match        *://*.insidetheloudhouse.com/*
// @match        *://interheron.com/*
// @match        *://*.interheron.com/*
// @match        *://jaysjournal.com/*
// @match        *://*.jaysjournal.com/*
// @match        *://jetswhiteout.com/*
// @match        *://*.jetswhiteout.com/*
// @match        *://justblogbaby.com/*
// @match        *://*.justblogbaby.com/*
// @match        *://kardashiandish.com/*
// @match        *://*.kardashiandish.com/*
// @match        *://kckingdom.com/*
// @match        *://*.kckingdom.com/*
// @match        *://keepingitheel.com/*
// @match        *://*.keepingitheel.com/*
// @match        *://kingjamesgospel.com/*
// @match        *://*.kingjamesgospel.com/*
// @match        *://kingsofkauffman.com/*
// @match        *://*.kingsofkauffman.com/*
// @match        *://krakenchronicle.com/*
// @match        *://*.krakenchronicle.com/*
// @match        *://lakeshowlife.com/*
// @match        *://*.lakeshowlife.com/*
// @match        *://lasportshub.com/*
// @match        *://*.lasportshub.com/*
// @match        *://lastnighton.com/*
// @match        *://*.lastnighton.com/*
// @match        *://lawlessrepublic.com/*
// @match        *://*.lawlessrepublic.com/*
// @match        *://lobandsmash.com/*
// @match        *://*.lobandsmash.com/*
// @match        *://localpov.com/*
// @match        *://*.localpov.com/*
// @match        *://lombardiave.com/*
// @match        *://*.lombardiave.com/*
// @match        *://mancitysquare.com/*
// @match        *://*.mancitysquare.com/*
// @match        *://marlinmaniac.com/*
// @match        *://*.marlinmaniac.com/*
// @match        *://maroonandwhitenation.com/*
// @match        *://*.maroonandwhitenation.com/*
// @match        *://milehighsticking.com/*
// @match        *://*.milehighsticking.com/*
// @match        *://mlsmultiplex.com/*
// @match        *://*.mlsmultiplex.com/*
// @match        *://motorcitybengals.com/*
// @match        *://*.motorcitybengals.com/*
// @match        *://musketfire.com/*
// @match        *://*.musketfire.com/*
// @match        *://netflixlife.com/*
// @match        *://*.netflixlife.com/*
// @match        *://newcastletoons.com/*
// @match        *://*.newcastletoons.com/*
// @match        *://nflmocks.com/*
// @match        *://*.nflmocks.com/*
// @match        *://nflspinzone.com/*
// @match        *://*.nflspinzone.com/*
// @match        *://ninernoise.com/*
// @match        *://*.ninernoise.com/*
// @match        *://nolanwritin.com/*
// @match        *://*.nolanwritin.com/*
// @match        *://northbankrsl.com/*
// @match        *://*.northbankrsl.com/*
// @match        *://nothinbutnets.com/*
// @match        *://*.nothinbutnets.com/*
// @match        *://nugglove.com/*
// @match        *://*.nugglove.com/*
// @match        *://octopusthrower.com/*
// @match        *://*.octopusthrower.com/*
// @match        *://oilonwhyte.com/*
// @match        *://*.oilonwhyte.com/*
// @match        *://oldjuve.com/*
// @match        *://*.oldjuve.com/*
// @match        *://onechicagocenter.com/*
// @match        *://*.onechicagocenter.com/*
// @match        *://orangeintheoven.com/*
// @match        *://*.orangeintheoven.com/*
// @match        *://orlandomagicdaily.com/*
// @match        *://*.orlandomagicdaily.com/*
// @match        *://otowns11.com/*
// @match        *://*.otowns11.com/*
// @match        *://paininthearsenal.com/*
// @match        *://*.paininthearsenal.com/*
// @match        *://pelicandebrief.com/*
// @match        *://*.pelicandebrief.com/*
// @match        *://penslabyrinth.com/*
// @match        *://*.penslabyrinth.com/*
// @match        *://phinphanatic.com/*
// @match        *://*.phinphanatic.com/*
// @match        *://pippenainteasy.com/*
// @match        *://*.pippenainteasy.com/*
// @match        *://pistonpowered.com/*
// @match        *://*.pistonpowered.com/*
// @match        *://playingfor90.com/*
// @match        *://*.playingfor90.com/*
// @match        *://pokespost.com/*
// @match        *://*.pokespost.com/*
// @match        *://precincttv.com/*
// @match        *://*.precincttv.com/*
// @match        *://predlines.com/*
// @match        *://*.predlines.com/*
// @match        *://predominantlyorange.com/*
// @match        *://*.predominantlyorange.com/*
// @match        *://princerupertstower.com/*
// @match        *://*.princerupertstower.com/*
// @match        *://progolfnow.com/*
// @match        *://*.progolfnow.com/*
// @match        *://psgpost.com/*
// @match        *://*.psgpost.com/*
// @match        *://puckettspond.com/*
// @match        *://*.puckettspond.com/*
// @match        *://puckprose.com/*
// @match        *://*.puckprose.com/*
// @match        *://pucksandpitchforks.com/*
// @match        *://*.pucksandpitchforks.com/*
// @match        *://pucksofafeather.com/*
// @match        *://*.pucksofafeather.com/*
// @match        *://raisingzona.com/*
// @match        *://*.raisingzona.com/*
// @match        *://ramblinfan.com/*
// @match        *://*.ramblinfan.com/*
// @match        *://ranchesandreins.com/*
// @match        *://*.ranchesandreins.com/*
// @match        *://raptorsrapture.com/*
// @match        *://*.raptorsrapture.com/*
// @match        *://rayscoloredglasses.com/*
// @match        *://*.rayscoloredglasses.com/*
// @match        *://razorbackers.com/*
// @match        *://*.razorbackers.com/*
// @match        *://redbirdrants.com/*
// @match        *://*.redbirdrants.com/*
// @match        *://reddevilarmada.com/*
// @match        *://*.reddevilarmada.com/*
// @match        *://redshirtsalwaysdie.com/*
// @match        *://*.redshirtsalwaysdie.com/*
// @match        *://reignoftroy.com/*
// @match        *://*.reignoftroy.com/*
// @match        *://releasetheknappen.com/*
// @match        *://*.releasetheknappen.com/*
// @match        *://reportingkc.com/*
// @match        *://*.reportingkc.com/*
// @match        *://reviewingthebrew.com/*
// @match        *://*.reviewingthebrew.com/*
// @match        *://rhymejunkie.com/*
// @match        *://*.rhymejunkie.com/*
// @match        *://riggosrag.com/*
// @match        *://*.riggosrag.com/*
// @match        *://rinkroyalty.com/*
// @match        *://*.rinkroyalty.com/*
// @match        *://ripcityproject.com/*
// @match        *://*.ripcityproject.com/*
// @match        *://risingapple.com/*
// @match        *://*.risingapple.com/*
// @match        *://rubbingtherock.com/*
// @match        *://*.rubbingtherock.com/*
// @match        *://rumbunter.com/*
// @match        *://*.rumbunter.com/*
// @match        *://rushthekop.com/*
// @match        *://*.rushthekop.com/*
// @match        *://sabrenoise.com/*
// @match        *://*.sabrenoise.com/*
// @match        *://saintsmarching.com/*
// @match        *://*.saintsmarching.com/*
// @match        *://saturdayblitz.com/*
// @match        *://*.saturdayblitz.com/*
// @match        *://scarletandgame.com/*
// @match        *://*.scarletandgame.com/*
// @match        *://section215.com/*
// @match        *://*.section215.com/*
// @match        *://senshot.com/*
// @match        *://*.senshot.com/*
// @match        *://showsnob.com/*
// @match        *://*.showsnob.com/*
// @match        *://sidelionreport.com/*
// @match        *://*.sidelionreport.com/*
// @match        *://sircharlesincharge.com/*
// @match        *://*.sircharlesincharge.com/*
// @match        *://skyscraperblues.com/*
// @match        *://*.skyscraperblues.com/*
// @match        *://slapthesign.com/*
// @match        *://*.slapthesign.com/*
// @match        *://soaringdownsouth.com/*
// @match        *://*.soaringdownsouth.com/*
// @match        *://sodomojo.com/*
// @match        *://*.sodomojo.com/*
// @match        *://southboundanddown.com/*
// @match        *://*.southboundanddown.com/*
// @match        *://southsideshowdown.com/*
// @match        *://*.southsideshowdown.com/*
// @match        *://spacecityscoop.com/*
// @match        *://*.spacecityscoop.com/*
// @match        *://spartanavenue.com/*
// @match        *://*.spartanavenue.com/*
// @match        *://sportdfw.com/*
// @match        *://*.sportdfw.com/*
// @match        *://stairwayto11.com/*
// @match        *://*.stairwayto11.com/*
// @match        *://starsandsticks.com/*
// @match        *://*.starsandsticks.com/*
// @match        *://stillcurtain.com/*
// @match        *://*.stillcurtain.com/*
// @match        *://stormininnorman.com/*
// @match        *://*.stormininnorman.com/*
// @match        *://stormthepaint.com/*
// @match        *://*.stormthepaint.com/*
// @match        *://stripehype.com/*
// @match        *://*.stripehype.com/*
// @match        *://survivingtribal.com/*
// @match        *://*.survivingtribal.com/*
// @match        *://swarmandsting.com/*
// @match        *://*.swarmandsting.com/*
// @match        *://teaandbanter.com/*
// @match        *://*.teaandbanter.com/*
// @match        *://tenntruth.com/*
// @match        *://*.tenntruth.com/*
// @match        *://terrapinstationmd.com/*
// @match        *://*.terrapinstationmd.com/*
// @match        *://thatballsouttahere.com/*
// @match        *://*.thatballsouttahere.com/*
// @match        *://thecanuckway.com/*
// @match        *://*.thecanuckway.com/*
// @match        *://thecelticbhoys.com/*
// @match        *://*.thecelticbhoys.com/*
// @match        *://thehuskyhaul.com/*
// @match        *://*.thehuskyhaul.com/*
// @match        *://thejetpress.com/*
// @match        *://*.thejetpress.com/*
// @match        *://thejnotes.com/*
// @match        *://*.thejnotes.com/*
// @match        *://thelandryhat.com/*
// @match        *://*.thelandryhat.com/*
// @match        *://theparentwatch.com/*
// @match        *://*.theparentwatch.com/*
// @match        *://thepewterplank.com/*
// @match        *://*.thepewterplank.com/*
// @match        *://theprideoflondon.com/*
// @match        *://*.theprideoflondon.com/*
// @match        *://therattrick.com/*
// @match        *://*.therattrick.com/*
// @match        *://therealchamps.com/*
// @match        *://*.therealchamps.com/*
// @match        *://thesixersense.com/*
// @match        *://*.thesixersense.com/*
// @match        *://thesmokingcuban.com/*
// @match        *://*.thesmokingcuban.com/*
// @match        *://thetimberlean.com/*
// @match        *://*.thetimberlean.com/*
// @match        *://thetopflight.com/*
// @match        *://*.thetopflight.com/*
// @match        *://theviewfromavalon.com/*
// @match        *://*.theviewfromavalon.com/*
// @match        *://thevikingage.com/*
// @match        *://*.thevikingage.com/*
// @match        *://throughthephog.com/*
// @match        *://*.throughthephog.com/*
// @match        *://thunderousintentions.com/*
// @match        *://*.thunderousintentions.com/*
// @match        *://tipofthetower.com/*
// @match        *://*.tipofthetower.com/*
// @match        *://titansized.com/*
// @match        *://*.titansized.com/*
// @match        *://torontoreds.com/*
// @match        *://*.torontoreds.com/*
// @match        *://torotimes.com/*
// @match        *://*.torotimes.com/*
// @match        *://tripsided.com/*
// @match        *://*.tripsided.com/*
// @match        *://trumanstales.com/*
// @match        *://*.trumanstales.com/*
// @match        *://undeadwalking.com/*
// @match        *://*.undeadwalking.com/*
// @match        *://underthelaces.com/*
// @match        *://*.underthelaces.com/*
// @match        *://unionandblue.com/*
// @match        *://*.unionandblue.com/*
// @match        *://valleyofthesuns.com/*
// @match        *://*.valleyofthesuns.com/*
// @match        *://vegashockeyknight.com/*
// @match        *://*.vegashockeyknight.com/*
// @match        *://venomstrikes.com/*
// @match        *://*.venomstrikes.com/*
// @match        *://victorybellrings.com/*
// @match        *://*.victorybellrings.com/*
// @match        *://vivaligamx.com/*
// @match        *://*.vivaligamx.com/*
// @match        *://whodatdish.com/*
// @match        *://*.whodatdish.com/*
// @match        *://wildcatbluenation.com/*
// @match        *://*.wildcatbluenation.com/*
// @match        *://winteriscoming.net/*
// @match        *://*.winteriscoming.net/*
// @match        *://withthefirstpick.com/*
// @match        *://*.withthefirstpick.com/*
// @match        *://wizofawes.com/*
// @match        *://*.wizofawes.com/*
// @match        *://wreckemred.com/*
// @match        *://*.wreckemred.com/*
// @match        *://writingillini.com/*
// @match        *://*.writingillini.com/*
// @match        *://dbltap.com/*
// @match        *://*.dbltap.com/*
// @match        *://fansidedmma.com/*
// @match        *://*.fansidedmma.com/*
// @match        *://poppicante.com/*
// @match        *://*.poppicante.com/*
// @match        *://yanksgoyard.com/*
// @match        *://*.yanksgoyard.com/*
// @match        *://yellowjackedup.com/*
// @match        *://*.yellowjackedup.com/*
// @match        *://zonazealots.com/*
// @match        *://*.zonazealots.com/*
// @match        *://aerotrader.com/*
// @match        *://*.aerotrader.com/*
// @match        *://atvtrader.com/*
// @match        *://*.atvtrader.com/*
// @match        *://commercialtrucktrader.com/*
// @match        *://*.commercialtrucktrader.com/*
// @match        *://cycletrader.com/*
// @match        *://*.cycletrader.com/*
// @match        *://doanhnghiepvn.vn/*
// @match        *://*.doanhnghiepvn.vn/*
// @match        *://equipmenttrader.com/*
// @match        *://*.equipmenttrader.com/*
// @match        *://happymoments.lol/*
// @match        *://*.happymoments.lol/*
// @match        *://modsfire.com/*
// @match        *://*.modsfire.com/*
// @match        *://movie-locations.com/*
// @match        *://*.movie-locations.com/*
// @match        *://newatlas.com/*
// @match        *://*.newatlas.com/*
// @match        *://notebookcheck.biz/*
// @match        *://*.notebookcheck.biz/*
// @match        *://notebookcheck.com/*
// @match        *://*.notebookcheck.com/*
// @match        *://notebookcheck.info/*
// @match        *://*.notebookcheck.info/*
// @match        *://notebookcheck.it/*
// @match        *://*.notebookcheck.it/*
// @match        *://notebookcheck.net/*
// @match        *://*.notebookcheck.net/*
// @match        *://notebookcheck.nl/*
// @match        *://*.notebookcheck.nl/*
// @match        *://notebookcheck.org/*
// @match        *://*.notebookcheck.org/*
// @match        *://notebookcheck.pl/*
// @match        *://*.notebookcheck.pl/*
// @match        *://notebookcheck.se/*
// @match        *://*.notebookcheck.se/*
// @match        *://notebookcheck-cn.com/*
// @match        *://*.notebookcheck-cn.com/*
// @match        *://notebookcheck-hu.com/*
// @match        *://*.notebookcheck-hu.com/*
// @match        *://notebookcheck-ru.com/*
// @match        *://*.notebookcheck-ru.com/*
// @match        *://notebookcheck-tr.com/*
// @match        *://*.notebookcheck-tr.com/*
// @match        *://persoenlich.com/*
// @match        *://*.persoenlich.com/*
// @match        *://programme-tv.net/*
// @match        *://*.programme-tv.net/*
// @match        *://pwctrader.com/*
// @match        *://*.pwctrader.com/*
// @match        *://snowmobiletrader.com/*
// @match        *://*.snowmobiletrader.com/*
// @match        *://steamidfinder.com/*
// @match        *://*.steamidfinder.com/*
// @match        *://techdico.com/*
// @match        *://*.techdico.com/*
// @match        *://universalis.fr/*
// @match        *://*.universalis.fr/*
// @match        *://wieistmeineip.at/*
// @match        *://*.wieistmeineip.at/*
// @match        *://wieistmeineip.ch/*
// @match        *://*.wieistmeineip.ch/*
// @match        *://wieistmeineip.de/*
// @match        *://*.wieistmeineip.de/*
// @match        *://bunshun.jp/*
// @match        *://*.bunshun.jp/*
// @match        *://gamewith.jp/*
// @match        *://*.gamewith.jp/*
// @match        *://teuteuf.fr/*
// @match        *://*.teuteuf.fr/*
// @match        *://arkadium.com/*
// @match        *://*.arkadium.com/*
// @match        *://hvac-talk.com/*
// @match        *://*.hvac-talk.com/*
// @match        *://thecelticblog.com/*
// @match        *://*.thecelticblog.com/*
// @match        *://alfa.lt/*
// @match        *://*.alfa.lt/*
// @match        *://bilis.lt/*
// @match        *://*.bilis.lt/*
// @match        *://etaplius.lt/*
// @match        *://*.etaplius.lt/*
// @match        *://new.mmm.lt/*
// @match        *://*.new.mmm.lt/*
// @match        *://raskakcija.lt/*
// @match        *://*.raskakcija.lt/*
// @match        *://sudokutable.com/*
// @match        *://*.sudokutable.com/*
// @match        *://superhonda.com/*
// @match        *://*.superhonda.com/*
// @match        *://thefirearmblog.com/*
// @match        *://*.thefirearmblog.com/*\
// @match        *://weldingweb.com/*
// @match        *://*.weldingweb.com/*
// @match        *://odyclub.com/*
// @match        *://*.odyclub.com/*
// @match        *://minecraftskins.com/*
// @match        *://*.minecraftskins.com/*
// @match        *://razzball.com/*
// @match        *://*.razzball.com/*
// @match        *://avsforum.com/*
// @match        *://*.avsforum.com/*
// @match        *://dairygoatinfo.com/*
// @match        *://*.dairygoatinfo.com/*
// @match        *://diychatroom.com/*
// @match        *://*.diychatroom.com/*
// @match        *://mytractorforum.com/*
// @match        *://*.mytractorforum.com/*
// @match        *://skyscrapercity.com/*
// @match        *://*.skyscrapercity.com/*
// @match        *://speypages.com/*
// @match        *://*.speypages.com/*
// @match        *://techguy.org/*
// @match        *://*.techguy.org/*
// @match        *://techsupportforum.com/*
// @match        *://*.techsupportforum.com/*
// @match        *://vwvortex.com/*
// @match        *://*.vwvortex.com/*
// @match        *://300cforums.com/*
// @match        *://*.300cforums.com/*
// @match        *://a5oc.com/*
// @match        *://*.a5oc.com/*
// @match        *://acuraworld.com/*
// @match        *://*.acuraworld.com/*
// @match        *://airsoftsociety.com/*
// @match        *://*.airsoftsociety.com/*
// @match        *://allpar.com/*
// @match        *://*.allpar.com/*
// @match        *://aquaticplantcentral.com/*
// @match        *://*.aquaticplantcentral.com/*
// @match        *://astraownersnetwork.co.uk/*
// @match        *://*.astraownersnetwork.co.uk/*
// @match        *://babybmw.net/*
// @match        *://*.babybmw.net/*
// @match        *://beesource.com/*
// @match        *://*.beesource.com/*
// @match        *://bimmerwerkz.com/*
// @match        *://*.bimmerwerkz.com/*
// @match        *://can-amforum.com/*
// @match        *://*.can-amforum.com/*
// @match        *://canadianmoneyforum.com/*
// @match        *://*.canadianmoneyforum.com/*
// @match        *://catfish1.com/*
// @match        *://*.catfish1.com/*
// @match        *://chevymalibuforum.com/*
// @match        *://*.chevymalibuforum.com/*
// @match        *://chinacarforums.com/*
// @match        *://*.chinacarforums.com/*
// @match        *://chihuahua-people.com/*
// @match        *://*.chihuahua-people.com/*
// @match        *://coloradofans.com/*
// @match        *://*.coloradofans.com/*
// @match        *://digitalhome.ca/*
// @match        *://*.digitalhome.ca/*
// @match        *://fordescape.org/*
// @match        *://*.fordescape.org/*
// @match        *://fullsizebronco.com/*
// @match        *://*.fullsizebronco.com/*
// @match        *://mazda3revolution.com/*
// @match        *://*.mazda3revolution.com/*
// @match        *://mdxers.org/*
// @match        *://*.mdxers.org/*
// @match        *://rootzwiki.com/*
// @match        *://*.rootzwiki.com/*
// @match        *://theakforum.net/*
// @match        *://*.theakforum.net/*
// @match        *://trailvoy.com/*
// @match        *://*.trailvoy.com/*
// @match        *://invoice-generator.com/*
// @match        *://*.invoice-generator.com/*
// @match        *://namemc.com/*
// @match        *://*.namemc.com/*
// @match        *://hochi.news/*
// @match        *://*.hochi.news/*
// @match        *://tastesbetterfromscratch.com/*
// @match        *://*.tastesbetterfromscratch.com/*
// @match        *://weatherzone.com.au/*
// @match        *://*.weatherzone.com.au/*
// @match        *://variety.com/*
// @match        *://*.variety.com/*
// @match        *://doviz.com/*
// @match        *://*.doviz.com/*
// @match        *://scribd.com/*
// @match        *://*.scribd.com/*
// @match        *://dict.cc/*
// @match        *://*.dict.cc/*
// @match        *://calculatorsoup.com/*
// @match        *://*.calculatorsoup.com/*
// @match        *://boardingarea.com/*
// @match        *://*.boardingarea.com/*
//
// @description        tinyShield allows AdGuard, uBlock Origin, Brave and ABP to resist against Ad-Shield quickly.
// @description:ko     tinyShield는 AdGuard, uBlock Origin, Brave 와 ABP가 애드쉴드에 빠르게 저항할 수 있도록 합니다.
// @description:ja     tinyShieldを使うと、AdGuard, uBlock Origin, Brave, およびABPがAd-Shieldに素早く対抗できます。
//
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==
(()=>{function CountCommonStrings(ArrayA,ArrayB){let SetB=new Set(ArrayB);return new Set(ArrayA.filter(Item=>SetB.has(Item))).size}function CheckDepthInASWeakMap(Args){if(typeof Args[0]!="object"||CountCommonStrings(["device","id","imp","regs","site","source"],Object.keys(Args[0]))<5)return!1;let ASBannerFrameIdRegExp=/^[0-9]+\/[a-zA-Z0-9]+\/[a-zA-Z0-9]+\/[a-z0-9-\(\)]+\/[a-zA-Z0-9_]+_slot[0-9]+_+/;return!(typeof Object.keys(Args[0]).find(Arg=>typeof Args[0][Arg]=="object"&&Array.isArray(Args[0][Arg])&&Args[0][Arg].filter(SubArg=>typeof SubArg=="object"&&Object.keys(SubArg).filter(InnerArg=>typeof InnerArg=="string"&&OriginalRegExpTest.call(ASBannerFrameIdRegExp,InnerArg))).length>=1)>"u")}var Win=typeof unsafeWindow<"u"?unsafeWindow:window,OriginalRegExpTest=Win.RegExp.prototype.test;function RunTinyShieldUserscript(BrowserWindow,UserscriptName="tinyShield"){let OriginalArrayToString=BrowserWindow.Array.prototype.toString,OriginalRegExpTest2=BrowserWindow.RegExp.prototype.test,ProtectedFunctionStrings=["toString","get","set"];BrowserWindow.Function.prototype.toString=new Proxy(BrowserWindow.Function.prototype.toString,{apply(Target,ThisArg,Args){return ProtectedFunctionStrings.includes(ThisArg.name)?`function ${ThisArg.name}() { [native code] }`:Reflect.apply(Target,ThisArg,Args)}});let ASInitPositiveRegExps=[[/[a-zA-Z0-9]+ *=> *{ *const *[a-zA-Z0-9]+ *= *[a-zA-Z0-9]+ *; *if/,/===? *[a-zA-Z0-9]+ *\[ *[a-zA-Z0-9]+\( *[0-9a-z]+ *\) *\] *\) *return *[a-zA-Z0-9]+ *\( *{ *('|")?inventoryId('|")? *:/,/{ *('|")?inventoryId('|")? *: *this *\[[a-zA-Z0-9]+ *\( *[0-9a-z]+ *\) *\] *, *\.\.\. *[a-zA-Z0-9]+ *\[ *[a-zA-Z0-9]+ *\( *[0-9a-z]+ * *\) *\] *} *\)/]];BrowserWindow.Map.prototype.get=new Proxy(BrowserWindow.Map.prototype.get,{apply(Target,ThisArg,Args){if(Args.length>0&&typeof Args[0]!="function")return Reflect.apply(Target,ThisArg,Args);let ArgText=OriginalArrayToString.call(Args);if(ASInitPositiveRegExps.filter(ASInitPositiveRegExp=>ASInitPositiveRegExp.filter(Index=>OriginalRegExpTest2.call(Index,ArgText)).length>=2).length===1)throw console.debug(`[${UserscriptName}]: Map.prototype.get:`,ThisArg,Args),new Error;return Reflect.apply(Target,ThisArg,Args)}});let ASReinsertedAdvInvenPositiveRegExps=[[/inventory_id,[a-zA-Z0-9-]+\/[a-zA-Z0-9]+\/[a-zA-Z0-9]+/,/inventory_id,[a-zA-Z0-9-]+\/[a-zA-Z0-9]+\/[a-zA-Z0-9]+/,/inventory_id,[a-zA-Z0-9-]+\/[a-zA-Z0-9]+\/[a-zA-Z0-9]+/],[/[a-z0-9A-Z]+\.setAttribute\( *('|")onload('|") *, *('|")! *async *function\( *\) *\{ *let */,/confirm\( *[A-Za-z0-9]+ *\) *\) *{ *const *[A-Za-z0-9]+ *= *new *[A-Za-z0-9]+\.URL\(('|")https:\/\/report\.error-report\.com\//,/\.forEach *\( *\( *[A-Za-z0-9]+ *=> *[A-Za-z0-9]+\.remove *\( *\) *\) *\) *\) *, *[0-9a-f]+ *\) *; *const *[A-Za-z0-9]+ *= *await *\( *await *fetch *\(/]];BrowserWindow.Map.prototype.set=new Proxy(BrowserWindow.Map.prototype.set,{apply(Target,ThisArg,Args){let ArgText="";try{ArgText=OriginalArrayToString.call(Args)}catch{console.warn(`[${UserscriptName}]: Map.prototype.set:`,ThisArg,Args)}if(ASReinsertedAdvInvenPositiveRegExps.filter(ASReinsertedAdvInvenPositiveRegExp=>ASReinsertedAdvInvenPositiveRegExp.filter(Index=>OriginalRegExpTest2.call(Index,ArgText)).length>=3).length===1)throw console.debug(`[${UserscriptName}]: Map.prototype.set:`,ThisArg,Args),new Error;return Reflect.apply(Target,ThisArg,Args)}}),BrowserWindow.WeakMap.prototype.set=new Proxy(BrowserWindow.WeakMap.prototype.set,{apply(Target,ThisArg,Args){if(CheckDepthInASWeakMap(Args))throw console.debug(`[${UserscriptName}]: WeakMap.prototype.set:`,ThisArg,Args),new Error;return Reflect.apply(Target,ThisArg,Args)}});let ASTimerRegExps=[[/async *\( *\) *=> *{ *const *[A-Za-z0-9]+ *= *[A-Za-z0-9]+ *; *await *[A-Za-z0-9]+ *\( *\)/,/; *await *[A-Za-z0-9]+ *\( *\) *, *[A-Za-z0-9]+ *\( *! *1 *, *new *Error *\( *[A-Za-z0-9]+ *\( *[0-9a-f]+ *\) *\) *\) *}/,/ *\) *\) *\) *}/]];BrowserWindow.setTimeout=new Proxy(BrowserWindow.setTimeout,{apply(Target,ThisArg,Args){if(ASTimerRegExps.filter(ASTimerRegExp=>ASTimerRegExp.filter(Index=>Index.test(Args[0].toString())).length>=3).length===1){console.debug(`[${UserscriptName}]: setTimeout:`,Args);return}return Reflect.apply(Target,ThisArg,Args)}}),BrowserWindow.setInterval=new Proxy(BrowserWindow.setInterval,{apply(Target,ThisArg,Args){if(ASTimerRegExps.filter(ASTimerRegExp=>ASTimerRegExp.filter(Index=>Index.test(Args[0].toString())).length>=3).length===1){console.debug(`[${UserscriptName}]: setInterval:`,Args);return}return Reflect.apply(Target,ThisArg,Args)}})}RunTinyShieldUserscript(Win);})();
